### ISSUE TITLE
Pequeñas correcciones

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twE105-omar-edu-nacho#1]
Está muy bien, pero debéis quitar estas dos frases del título:
> Dependiendo de la dificultad del proyecto según lo vayamos desarrollando agregaremos o modificaremos algunos juegos. Haremos un submenú para elegir dichos juegos.
Y ponerlas en objetivos del tipo:
- Desarrollar varios juegos para la consola.
- Crear un menú donde se podrá seleccionar cada uno de estos juegos.

Acordaos tembién de cambiarle el nombre al repositorio tipo:
twE105-consola-arcade   o algo del estilo.
Recordad que esto se puede hacer desde Settings, la pestaña a la derecha de donde pone (<> Code)

Seguid así. 👍

**Comment by oscarperpinan** [comment]
Además, en README debéis sustituir la frase "Título del trabajo" por el título de vuestro trabajo.

**Comment by dudualbelda07** [comment]
> Está muy bien, pero debéis quitar estas dos frases del título:
> 
> Dependiendo de la dificultad del proyecto según lo vayamos desarrollando agregaremos o modificaremos algunos juegos. Haremos un submenú para elegir dichos juegos.
> Y ponerlas en objetivos del tipo:
> 
> 
> Desarrollar varios juegos para la consola.
> Crear un menú donde se podrá seleccionar cada uno de estos juegos.
> 
> Acordaos tembién de cambiarle el nombre al repositorio tipo:
> twE105-consola-arcade   o algo del estilo.
> Recordad que esto se puede hacer desde Settings, la pestaña a la derecha de donde pone (<> Code)
> Seguid así. 👍

Buenas tardes, no somos capaces de cambiar el nombre del repositorio.

**Comment by dudualbelda07** [comment]
No podemos cambiar el nombre del repositorio, hemos hablado con Oscar y está de acuerdo con dejar así el nombre
