### ISSUE TITLE
Problema con ahorcado

### ISSUE THREAD

**Issue by dudualbelda07** [aigora/twE105-omar-edu-nacho#3]
Omar, Nacho, el ahorcado esta terminado pero tiene un error a la hora de contar los fallos
Si encontrais el/los fallos comentádmelo y lo arreglo
Escribidme por WhatsApp con cualquier otro problema

**Comment by oelshami** [comment]
Hola buenas,

Ya encontré el fallo (estaba en la función ahorcado), te recomiendo ver la history para entenderlo mejor,

Un saludo.

**Comment by dudualbelda07** [comment]
Sigue teniendo un problema con el tema de los fallos
